(() => {
"use strict";
const SAVE_KEY="maseki_inflation_rpg_v02";
const HERO_IMAGE_KEY="maseki_rpg_hero_image_v02";
const $=id=>document.getElementById(id);

const LOCATIONS=[
{id:"grass",name:"はじまりの草原",text:"弱い魔物が出る。育成の起点。",minLevel:1,color:["#163824","#141a30"],enemies:["slime","hornRabbit","goblinRaider"]},
{id:"forest",name:"黒い森",text:"影の魔物が棲む森。技経験値を稼ぎやすい。",minLevel:4,color:["#13251a","#251429"],enemies:["shadowWolf","poisonMoth","mushroomBeast","stoneTurtle"]},
{id:"cave",name:"魔石洞窟",text:"魔石を多く落とす敵がいる。装備資金稼ぎ向け。",minLevel:8,color:["#20304a","#151525"],enemies:["masekiGolem","crystalBat","ghostWisp"]},
{id:"ruins",name:"古代廃墟",text:"素材が優秀。仲間解放の条件素材も落ちる。",minLevel:14,color:["#3a3324","#151522"],enemies:["ancientSoldier","runeWisp","skeletonSwordsman"]},
{id:"dragonValley",name:"竜の谷",text:"強敵地帯。強力な竜素材と技を狙える。",minLevel:24,color:["#49211d","#1a1324"],enemies:["lesserDragon","rainbowDrake","fireLizard","thunderHawk"]},
{id:"divine",name:"白黒虹の神域",text:"インフレの先。桁が跳ね上がる終盤地帯。",minLevel:40,color:["#e8e8e8","#050505"],enemies:["voidAngel","godFragment","iceSpirit","corruptedTreant"]}
];

const ENEMIES={
slime:{name:"スライム",maxHp:35,atk:7,def:1,exp:7,materials:[["ぷるぷる核",1,.85]],learnSkill:"粘液弾",learnRate:.04,portrait:"粘液",img:"./assets/enemy-sheet-1.png"},
hornRabbit:{name:"角ウサギ",maxHp:55,atk:10,def:2,exp:11,materials:[["小さな角",1,.7],["柔らかい毛皮",1,.45]],learnSkill:"突進",learnRate:.035,portrait:"角兎",img:"./assets/enemy-sheet-1.png"},
shadowWolf:{name:"影狼",maxHp:120,atk:22,def:5,exp:30,materials:[["影狼の牙",1,.7],["黒い毛皮",1,.55]],learnSkill:"シャドウバイト",learnRate:.035,portrait:"影狼",img:"./assets/enemy-sheet-1.png"},
poisonMoth:{name:"毒蛾",maxHp:95,atk:18,def:3,exp:26,materials:[["毒鱗粉",1,.72]],learnSkill:"毒鱗粉",learnRate:.04,portrait:"毒蛾",img:"./assets/enemy-sheet-1.png"},
crystalBat:{name:"水晶コウモリ",maxHp:190,atk:45,def:8,exp:76,materials:[["水晶の羽",1,.65],["魔石の欠片",1,.45]],learnSkill:"クリスタルエッジ",learnRate:.032,portrait:"晶蝙",img:"./assets/enemy-sheet-1.png"},
skeletonSwordsman:{name:"骸骨剣士",maxHp:180,atk:42,def:12,exp:65,materials:[["古びた骨",2,.8],["錆びた剣片",1,.45]],learnSkill:"ボーンスラッシュ",learnRate:.035,portrait:"骸剣",img:"./assets/enemy-sheet-1.png"},
ghostWisp:{name:"ゴーストウィスプ",maxHp:150,atk:48,def:7,exp:72,materials:[["霊火の欠片",1,.72]],learnSkill:"霊火弾",learnRate:.033,portrait:"霊火",img:"./assets/enemy-sheet-1.png"},
mushroomBeast:{name:"マッシュビースト",maxHp:210,atk:36,def:18,exp:80,materials:[["毒キノコ傘",2,.7]],learnSkill:"胞子爆発",learnRate:.03,portrait:"茸獣",img:"./assets/enemy-sheet-1.png"},
goblinRaider:{name:"ゴブリンレイダー",maxHp:75,atk:16,def:4,exp:20,materials:[["粗末な刃",1,.55],["獣皮",1,.55]],learnSkill:"乱れ斬り",learnRate:.035,portrait:"小鬼",img:"./assets/enemy-sheet-1.png"},
stoneTurtle:{name:"ストーンタートル",maxHp:240,atk:26,def:35,exp:95,materials:[["硬い甲羅",1,.75],["苔むした石",2,.55]],learnSkill:"甲羅砕き",learnRate:.03,portrait:"石亀",img:"./assets/enemy-sheet-1.png"},
masekiGolem:{name:"魔石ゴーレム",maxHp:260,atk:40,def:16,exp:85,materials:[["魔石の欠片",2,.9],["硬い岩盤",1,.55]],learnSkill:"ストーンブレイク",learnRate:.035,portrait:"魔像",img:"./assets/enemy-sheet-2.png"},
ancientSoldier:{name:"古代兵",maxHp:520,atk:88,def:28,exp:210,materials:[["古代金属片",2,.78],["壊れた紋章",1,.35]],learnSkill:"古代剣技",learnRate:.03,portrait:"古兵",img:"./assets/enemy-sheet-2.png"},
runeWisp:{name:"ルーンウィスプ",maxHp:430,atk:105,def:18,exp:240,materials:[["ルーンの残滓",2,.75]],learnSkill:"ルーンバースト",learnRate:.03,portrait:"術光",img:"./assets/enemy-sheet-2.png"},
lesserDragon:{name:"レッサードラゴン",maxHp:1600,atk:280,def:80,exp:980,materials:[["竜鱗",2,.8],["竜牙",1,.55],["竜核",1,.15]],learnSkill:"竜爪撃",learnRate:.025,portrait:"竜",img:"./assets/enemy-sheet-2.png"},
rainbowDrake:{name:"虹鱗ドレイク",maxHp:2400,atk:380,def:110,exp:1500,materials:[["虹鱗",2,.7],["竜核",1,.22]],learnSkill:"虹鱗閃",learnRate:.023,portrait:"虹竜",img:"./assets/enemy-sheet-2.png"},
corruptedTreant:{name:"腐敗トレント",maxHp:3200,atk:520,def:220,exp:2100,materials:[["腐敗樹芯",2,.65],["紫樹液",1,.5]],learnSkill:"樹縛り",learnRate:.022,portrait:"腐樹",img:"./assets/enemy-sheet-2.png"},
fireLizard:{name:"炎尾リザード",maxHp:1800,atk:420,def:95,exp:1200,materials:[["炎尾の鱗",2,.7]],learnSkill:"フレイムテイル",learnRate:.025,portrait:"炎蜥",img:"./assets/enemy-sheet-2.png"},
iceSpirit:{name:"氷晶精霊",maxHp:5200,atk:980,def:360,exp:4200,materials:[["氷晶花",2,.7]],learnSkill:"アイスプリズム",learnRate:.02,portrait:"氷精",img:"./assets/enemy-sheet-2.png"},
thunderHawk:{name:"雷鳴ホーク",maxHp:2600,atk:720,def:160,exp:2400,materials:[["雷羽",2,.7]],learnSkill:"サンダーダイブ",learnRate:.022,portrait:"雷鷹",img:"./assets/enemy-sheet-2.png"},
voidAngel:{name:"虚無天使",maxHp:12000,atk:2200,def:800,exp:9000,materials:[["虚無の羽",2,.7],["神域片",1,.35]],learnSkill:"虚無光",learnRate:.018,portrait:"虚天",img:"./assets/enemy-sheet-2.png"},
godFragment:{name:"神の欠片",maxHp:28000,atk:4800,def:1600,exp:24000,materials:[["神域片",3,.8],["白黒虹核",1,.12]],learnSkill:"神片解放",learnRate:.012,portrait:"神片",img:"./assets/enemy-sheet-2.png"}
};

const SKILL_LIBRARY={
"虹斬り":{mp:5,power:1.8,base:12},
"粘液弾":{mp:4,power:1.25,base:8},"突進":{mp:5,power:1.45,base:10},"シャドウバイト":{mp:9,power:2.2,base:26},"毒鱗粉":{mp:8,power:1.9,base:20},"ストーンブレイク":{mp:12,power:2.8,base:45},"クリスタルエッジ":{mp:14,power:3.1,base:55},"古代剣技":{mp:20,power:4.1,base:120},"ルーンバースト":{mp:24,power:4.7,base:160},"竜爪撃":{mp:40,power:7.2,base:500},"虹鱗閃":{mp:55,power:9.5,base:900},"虚無光":{mp:120,power:18,base:3500},"神片解放":{mp:250,power:35,base:12000},
"ボーンスラッシュ":{mp:10,power:2.4,base:28},"霊火弾":{mp:11,power:2.6,base:35},"胞子爆発":{mp:12,power:2.5,base:42},"乱れ斬り":{mp:7,power:1.9,base:18},"甲羅砕き":{mp:12,power:3.0,base:45},"樹縛り":{mp:70,power:9.0,base:1200},"フレイムテイル":{mp:45,power:7.8,base:650},"アイスプリズム":{mp:90,power:12.0,base:2100},"サンダーダイブ":{mp:75,power:10.5,base:1600}
};

const SHOP_ITEMS=[
{id:"ironSword",name:"鉄の剣",slot:"weapon",price:80,stats:{atk:8}},
{id:"masekiBlade",name:"魔石刀",slot:"weapon",price:600,stats:{atk:55,maxMp:10}},
{id:"rainbowEdge",name:"虹刃の剣",slot:"weapon",price:4200,stats:{atk:360,maxMp:120}},
{id:"clothArmor",name:"旅人の服",slot:"armor",price:50,stats:{def:4,maxHp:20}},
{id:"blackCoat",name:"黒虹の外套",slot:"armor",price:900,stats:{def:60,maxHp:280}},
{id:"divineArmor",name:"神域装束",slot:"armor",price:12000,stats:{def:900,maxHp:5000,maxMp:500}},
{id:"stoneCharm",name:"魔石の護符",slot:"accessory",price:300,stats:{atk:10,def:10,maxMp:30}},
{id:"rainbowCharm",name:"白黒虹の環",slot:"accessory",price:9000,stats:{atk:700,def:500,maxHp:4000,maxMp:1000}},
{id:"potionPack",name:"回復薬セット",type:"consumable",price:120,amount:3}
];

const CRAFT_RECIPES=[
{id:"wolfBlade",name:"影狼牙の短剣",slot:"weapon",stats:{atk:95},costMoney:250,materials:{"影狼の牙":4,"黒い毛皮":2}},
{id:"golemArmor",name:"魔石岩盤鎧",slot:"armor",stats:{def:150,maxHp:600},costMoney:700,materials:{"魔石の欠片":8,"硬い岩盤":4}},
{id:"ancientSword",name:"古代紋章剣",slot:"weapon",stats:{atk:620,maxMp:140},costMoney:2500,materials:{"古代金属片":10,"壊れた紋章":2,"ルーンの残滓":4}},
{id:"dragonBlade",name:"竜牙虹刀",slot:"weapon",stats:{atk:2200,maxHp:1500},costMoney:9000,materials:{"竜牙":5,"竜鱗":12,"竜核":2,"虹鱗":4}},
{id:"godRing",name:"白黒虹核の指輪",slot:"accessory",stats:{atk:5000,def:3500,maxHp:20000,maxMp:5000},costMoney:50000,materials:{"白黒虹核":1,"神域片":12,"虚無の羽":8}}
];

const state=init();

const ALLIES=[
{id:"white",name:"白虹の剣姫",requirementText:"Lv8以上 / 500G / 小さな角×3 / 魔石刀を所持",canJoin:()=>state.player.level>=8&&state.player.money>=500&&mat("小さな角")>=3&&hasEquipment("masekiBlade"),cost:()=>{state.player.money-=500;removeMaterial("小さな角",3)},bonus:{atk:35,maxHp:150}},
{id:"black",name:"黒虹の魔女",requirementText:"Lv16以上 / 3000G / ルーンの残滓×6 / 黒虹の外套を所持",canJoin:()=>state.player.level>=16&&state.player.money>=3000&&mat("ルーンの残滓")>=6&&hasEquipment("blackCoat"),cost:()=>{state.player.money-=3000;removeMaterial("ルーンの残滓",6)},bonus:{atk:120,maxMp:500}},
{id:"dragon",name:"虹龍",requirementText:"Lv30以上 / 15000G / 竜核×3 / 虹鱗×8 / 竜牙虹刀を所持",canJoin:()=>state.player.level>=30&&state.player.money>=15000&&mat("竜核")>=3&&mat("虹鱗")>=8&&hasEquipment("dragonBlade"),cost:()=>{state.player.money-=15000;removeMaterial("竜核",3);removeMaterial("虹鱗",8)},bonus:{atk:1200,def:800,maxHp:9000}}
];

const QUESTS=[
{id:"slimeHunter",name:"草原の掃討",description:"スライムを5体倒す。報酬：200G、回復薬×2",done:()=>state.kills.slime>=5,reward:()=>{state.player.money+=200;state.player.items.potion+=2}},
{id:"golemCore",name:"魔石洞窟の調査",description:"魔石ゴーレムを3体倒す。報酬：1500G、魔石の欠片×5",done:()=>state.kills.masekiGolem>=3,reward:()=>{state.player.money+=1500;addMaterial("魔石の欠片",5)}},
{id:"dragonProof",name:"竜の谷の証明",description:"レッサードラゴンを2体倒す。報酬：8000G、竜核×1",done:()=>state.kills.lesserDragon>=2,reward:()=>{state.player.money+=8000;addMaterial("竜核",1)}}
];

const audio={enabled:false,ctx:null,bgmTimer:null};

function init(){return{currentLocation:"grass",enemy:null,battleOver:false,kills:{},claimedQuests:{},unlockedAllies:{},player:{name:"白黒虹の主人公",level:1,exp:0,nextExp:25,hp:100,maxHp:100,mp:30,maxMp:30,atk:12,def:3,money:0,stones:0,totalAbsorbed:0,items:{potion:5},materials:{},inventory:{},equipment:{weapon:null,armor:null,accessory:null},skills:{"虹斬り":{name:"虹斬り",level:1,exp:0,nextExp:10}},skillSlots:["虹斬り",null,null,null,null,null,null,null,null]}}}
function migrate(){if(!state.player.skillSlots)state.player.skillSlots=["虹斬り",null,null,null,null,null,null,null,null];if(state.player.skills&&state.player.skills["虹斬り"]&&!state.player.skillSlots.includes("虹斬り"))state.player.skillSlots[0]="虹斬り"}
function format(n){n=Math.floor(Number(n)||0);if(n<1e4)return String(n);if(n>=1e12)return(n/1e12).toFixed(2).replace(/\.00$/,"")+"兆";if(n>=1e8)return(n/1e8).toFixed(2).replace(/\.00$/,"")+"億";return(n/1e4).toFixed(2).replace(/\.00$/,"")+"万"}
function rand(a,b){return Math.floor(Math.random()*(b-a+1))+a}function choice(a){return a[Math.floor(Math.random()*a.length)]}function loc(){return LOCATIONS.find(l=>l.id===state.currentLocation)||LOCATIONS[0]}
function totals(){const p=state.player,b={maxHp:0,maxMp:0,atk:0,def:0};["weapon","armor","accessory"].forEach(s=>{const it=findItem(p.equipment[s]);if(it&&it.stats)Object.entries(it.stats).forEach(([k,v])=>b[k]=(b[k]||0)+v)});ALLIES.forEach(a=>{if(state.unlockedAllies[a.id])Object.entries(a.bonus).forEach(([k,v])=>b[k]=(b[k]||0)+v)});return{maxHp:p.maxHp+b.maxHp,maxMp:p.maxMp+b.maxMp,atk:p.atk+b.atk,def:p.def+b.def}}
function basicStoneDrop(){let amount=1;if(Math.random()<.16)amount++;if(Math.random()<.045)amount+=rand(1,3);if(Math.random()<.01)amount+=rand(4,8);return amount}
function spawnEnemy(){const l=loc(),id=choice(l.enemies),e=ENEMIES[id],scale=1+Math.max(0,state.player.level-l.minLevel)*.11;state.enemy={id,name:e.name,portrait:e.portrait,img:e.img||"",maxHp:Math.floor(e.maxHp*scale),hp:Math.floor(e.maxHp*scale),atk:Math.floor(e.atk*scale),def:Math.floor(e.def*scale),exp:Math.floor(e.exp*scale),stones:basicStoneDrop(),materials:e.materials,learnSkill:e.learnSkill,learnRate:e.learnRate};state.battleOver=false;log(`${l.name}：${state.enemy.name}が現れた。`);sfx("spawn");render();toast(`${state.enemy.name}が出現`)}
function canAct(req=true){if(req&&(!state.enemy||state.battleOver)){log("敵がいない。次の敵を探そう。","bad");return false}return true}
function attack(){if(!canAct())return;const t=totals(),d=Math.max(1,rand(Math.floor(t.atk*.85),Math.floor(t.atk*1.15))-Math.floor(state.enemy.def*.35));hit(d,"攻撃");sfx("attack");heroSlash();if(!state.battleOver)enemyTurn();render()}
function useSkill(name){if(!canAct())return;const s=state.player.skills[name],lib=SKILL_LIBRARY[name];if(!s||!lib)return log("その技はまだ使えない。","bad");if(state.player.mp<lib.mp)return log(`MP不足。${name}はMP${lib.mp}必要。`,"bad");state.player.mp-=lib.mp;const t=totals(),bonus=1+(s.level-1)*.22,d=Math.max(1,Math.floor((t.atk*lib.power+lib.base)*bonus*(rand(90,115)/100))-Math.floor(state.enemy.def*.2));skillExp(name,5+s.level);hit(d,`${name} Lv${s.level}`);sfx("skill");heroSlash();anim($("scene"),"flash");if(!state.battleOver)enemyTurn();render()}
function hit(d,label){state.enemy.hp=Math.max(0,state.enemy.hp-d);log(`${label}！ ${state.enemy.name}に${format(d)}ダメージ。`);anim($("enemyImage"),"hit");anim($("enemyFallback"),"shake");if(state.enemy.hp<=0)victory()}
function enemyTurn(){const t=totals(),d=Math.max(1,rand(Math.floor(state.enemy.atk*.85),Math.floor(state.enemy.atk*1.15))-Math.floor(t.def*.45));state.player.hp=Math.max(0,state.player.hp-d);log(`${state.enemy.name}の攻撃。${format(d)}ダメージ。`,"bad");sfx("hit");if(state.player.hp<=0){state.battleOver=true;state.player.stones=Math.max(0,Math.floor(state.player.stones*.9));const t2=totals();state.player.hp=Math.floor(t2.maxHp*.5);state.player.mp=Math.floor(t2.maxMp*.5);log("倒れた……所持魔石の10%を失い、HP/MP半分で復帰。","bad");sfx("down")}}
function victory(){const e=state.enemy;state.battleOver=true;state.kills[e.id]=(state.kills[e.id]||0)+1;state.player.exp+=e.exp;state.player.stones+=e.stones;log(`${e.name}撃破！ EXP${format(e.exp)} / 魔石${format(e.stones)}個獲得。`,"good");sfx("win");e.materials.forEach(([m,a,r])=>{if(Math.random()<=r){const q=a+(Math.random()<.15?1:0);addMaterial(m,q);log(`素材「${m}」×${q}入手。`,"rare")}});levelUp();questCheck()}
function levelUp(){while(state.player.exp>=state.player.nextExp){state.player.exp-=state.player.nextExp;state.player.level++;state.player.nextExp=Math.floor(state.player.nextExp*1.35+state.player.level*12);state.player.maxHp=Math.floor(state.player.maxHp*1.18+18);state.player.maxMp=Math.floor(state.player.maxMp*1.14+6);state.player.atk=Math.floor(state.player.atk*1.16+5);state.player.def=Math.floor(state.player.def*1.13+3);const t=totals();state.player.hp=t.maxHp;state.player.mp=t.maxMp;log(`レベルアップ！ Lv${state.player.level}`,"rare");sfx("level");toast(`Lv${state.player.level} 到達`)}}
function skillExp(n,a){const s=state.player.skills[n];s.exp+=a;while(s.exp>=s.nextExp){s.exp-=s.nextExp;s.level++;s.nextExp=Math.floor(s.nextExp*1.45+s.level*8);log(`技「${n}」がLv${s.level}に上昇！`,"rare");sfx("level")}}
function absorb(mode="some"){if(state.player.stones<=0)return log("吸収できる魔石がない。","bad");const a=mode==="all"?state.player.stones:Math.max(1,Math.floor(state.player.stones*.1));state.player.stones-=a;state.player.totalAbsorbed+=a;const hp=a*3,mp=Math.floor(a*.8),atk=Math.max(1,Math.floor(a*.35)),def=Math.max(1,Math.floor(a*.22));state.player.maxHp+=hp;state.player.maxMp+=mp;state.player.atk+=atk;state.player.def+=def;const t=totals();state.player.hp=Math.min(t.maxHp,state.player.hp+hp);state.player.mp=Math.min(t.maxMp,state.player.mp+mp);log(`魔石${format(a)}個吸収。HP+${format(hp)} MP+${format(mp)} 攻撃+${format(atk)} 防御+${format(def)}。`,"rare");sfx("absorb");if(state.enemy&&state.enemy.learnSkill&&!state.player.skills[state.enemy.learnSkill]){if(Math.random()<state.enemy.learnRate){learnSkill(state.enemy.learnSkill)}else log(`${state.enemy.learnSkill}の気配を感じたが、習得ならず。`)}render()}
function learnSkill(name){state.player.skills[name]={name,level:1,exp:0,nextExp:14};const empty=state.player.skillSlots.findIndex(x=>!x);if(empty>=0)state.player.skillSlots[empty]=name;log(`魔石から技「${name}」を習得！${empty>=0?" 技セットに自動装備。":""}`,"rare");sfx("learn");toast(`新技：${name}`)}
function potion(){if(!canAct(false))return;if((state.player.items.potion||0)<=0)return log("回復薬がない。","bad");const t=totals(),h=Math.floor(t.maxHp*.35);state.player.items.potion--;state.player.hp=Math.min(t.maxHp,state.player.hp+h);log(`回復薬使用。HP${format(h)}回復。`,"good");sfx("heal");if(state.enemy&&!state.battleOver)enemyTurn();render()}
function sell(v){const a=v==="all"?state.player.stones:Math.min(Number(v),state.player.stones);if(a<=0)return log("売れる魔石がない。","bad");state.player.stones-=a;state.player.money+=a*8;log(`魔石${format(a)}個を売却。${format(a*8)}G獲得。`,"good");sfx("coin");render()}
function buy(id){const it=SHOP_ITEMS.find(i=>i.id===id);if(!it||state.player.money<it.price)return log("お金が足りない。","bad");state.player.money-=it.price;if(it.type==="consumable"){state.player.items.potion+=it.amount;log(`${it.name}購入。回復薬+${it.amount}`,"good")}else{state.player.inventory[it.id]=true;log(`${it.name}購入。`,"good")}sfx("coin");render()}
function equip(id){const it=findItem(id);if(!it||!it.slot||!state.player.inventory[id])return;state.player.equipment[it.slot]=id;normalize();log(`${it.name}を装備。`,"good");sfx("equip");render()}
function craft(id){const r=CRAFT_RECIPES.find(x=>x.id===id);if(!r||state.player.money<r.costMoney)return log("作成条件を満たしていない。","bad");for(const [m,a] of Object.entries(r.materials)){if(mat(m)<a)return log(`素材「${m}」不足。`,"bad")}state.player.money-=r.costMoney;Object.entries(r.materials).forEach(([m,a])=>removeMaterial(m,a));state.player.inventory[r.id]=true;log(`${r.name}を作成。`,"rare");sfx("craft");render()}
function join(id){const a=ALLIES.find(x=>x.id===id);if(!a||state.unlockedAllies[id])return;if(!a.canJoin())return log("加入条件を満たしていない。","bad");a.cost();state.unlockedAllies[id]=true;normalize();log(`${a.name}が加入！`,"rare");sfx("level");toast(`${a.name} 加入`);render()}
function questCheck(){QUESTS.forEach(q=>{if(!state.claimedQuests[q.id]&&q.done()){state.claimedQuests[q.id]=true;q.reward();log(`クエスト達成「${q.name}」！`,"rare");sfx("level")}})}
function move(id){const l=LOCATIONS.find(x=>x.id===id);if(!l)return;if(state.player.level<l.minLevel)return log(`${l.name}はLv${l.minLevel}から。`,"bad");state.currentLocation=id;state.enemy=null;state.battleOver=true;log(`${l.name}へ移動。`);sfx("move");tab("battle");render()}
function addMaterial(n,a){state.player.materials[n]=(state.player.materials[n]||0)+a}function removeMaterial(n,a){state.player.materials[n]=Math.max(0,(state.player.materials[n]||0)-a)}function mat(n){return state.player.materials[n]||0}
function findItem(id){return SHOP_ITEMS.find(i=>i.id===id)||CRAFT_RECIPES.find(i=>i.id===id)}function hasEquipment(id){return !!state.player.inventory[id]||Object.values(state.player.equipment).includes(id)}
function normalize(){const t=totals();state.player.hp=Math.min(state.player.hp,t.maxHp);state.player.mp=Math.min(state.player.mp,t.maxMp)}
function save(){localStorage.setItem(SAVE_KEY,JSON.stringify(state));log("保存しました。","good");toast("保存しました");sfx("coin")}
function load(){const raw=localStorage.getItem(SAVE_KEY);if(!raw)return log("保存データがありません。","bad");try{const data=JSON.parse(raw);Object.keys(state).forEach(k=>delete state[k]);Object.assign(state,data);migrate();log("読み込みました。","good");render()}catch{log("読み込み失敗。","bad")}}
function reset(){if(!confirm("初期化しますか？保存データも削除します。"))return;localStorage.removeItem(SAVE_KEY);const fresh=init();Object.keys(state).forEach(k=>delete state[k]);Object.assign(state,fresh);log("初期化しました。");spawnEnemy();render()}
function tab(n){document.querySelectorAll(".tab").forEach(b=>b.classList.toggle("active",b.dataset.tab===n));document.querySelectorAll(".tab-page").forEach(p=>p.classList.remove("active"));$(n+"Tab").classList.add("active")}
function setSkillSlot(i,name){if(name&&state.player.skillSlots.includes(name)){const old=state.player.skillSlots.indexOf(name);state.player.skillSlots[old]=null}state.player.skillSlots[i]=name||null;render()}
function unequipSkill(name){state.player.skillSlots=state.player.skillSlots.map(x=>x===name?null:x);render()}
function render(){migrate();const l=loc();$("scene").style.background=`linear-gradient(135deg,${l.color[0]},${l.color[1]})`;$("sceneName").textContent=l.name;$("sceneText").textContent=l.text;$("stripLevel").textContent=state.player.level;$("stripMoney").textContent=format(state.player.money);$("stripStones").textContent=format(state.player.stones);$("stripLocation").textContent=l.name;renderBattle();renderCommands();renderLocations();renderStats();renderSkills();renderMaterials();renderShop();renderCraft();renderEquipment();renderParty();renderQuests();renderImages()}
function renderBattle(){const t=totals();$("heroName").textContent=`${state.player.name} Lv${state.player.level}`;$("heroBars").innerHTML=bar("HP",state.player.hp,t.maxHp)+bar("MP",state.player.mp,t.maxMp)+bar("EXP",state.player.exp,state.player.nextExp);$("heroStats").innerHTML=row("攻撃",format(t.atk))+row("防御",format(t.def))+row("回復薬",state.player.items.potion||0);if(state.enemy){$("enemyFallback").textContent=state.enemy.portrait;$("enemyName").textContent=state.enemy.name;$("enemyBars").innerHTML=bar("HP",state.enemy.hp,state.enemy.maxHp);$("enemyStats").innerHTML=row("攻撃",format(state.enemy.atk))+row("防御",format(state.enemy.def))+row("吸収技",state.enemy.learnSkill);if(state.enemy.img){$("enemyImage").src=state.enemy.img;$("enemyImage").classList.add("show")}else $("enemyImage").classList.remove("show")}else{$("enemyImage").classList.remove("show");$("enemyFallback").textContent="探索";$("enemyName").textContent="敵なし";$("enemyBars").innerHTML=bar("HP",0,1);$("enemyStats").innerHTML=row("状態","次の敵を探そう")}}
function renderCommands(){const has=!!state.enemy&&!state.battleOver;const skillButtons=state.player.skillSlots.map((name,i)=>name?`<button data-use-skill="${name}" ${!has?"disabled":""}>${name}</button>`:"").join("");$("commandPad").innerHTML=`<button id="attackBtn">攻撃</button>${skillButtons}<button id="healBtn">回復薬</button><button id="absorbBtn">10%吸収</button><button id="nextBtn">次の敵</button>`;$("attackBtn").disabled=!has;$("attackBtn").onclick=attack;$("healBtn").onclick=potion;$("absorbBtn").onclick=()=>absorb("some");$("nextBtn").onclick=spawnEnemy;document.querySelectorAll("[data-use-skill]").forEach(b=>b.onclick=()=>useSkill(b.dataset.useSkill))}
function renderLocations(){$("locationList").innerHTML=LOCATIONS.map(l=>{const locked=state.player.level<l.minLevel;return `<article class="card"><h3>${l.name}</h3><p>${l.text}<br>${locked?`解放条件：Lv${l.minLevel}`:"移動可能"}</p><button data-location="${l.id}" ${locked?"disabled":""}>ここへ行く</button></article>`}).join("");document.querySelectorAll("[data-location]").forEach(b=>b.onclick=()=>move(b.dataset.location))}
function renderStats(){const t=totals();$("stats").innerHTML=row("Lv",state.player.level)+row("経験値",`${format(state.player.exp)} / ${format(state.player.nextExp)}`)+row("HP",`${format(state.player.hp)} / ${format(t.maxHp)}`)+row("MP",`${format(state.player.mp)} / ${format(t.maxMp)}`)+row("攻撃",format(t.atk))+row("防御",format(t.def))+row("撃破数",format(Object.values(state.kills).reduce((a,b)=>a+b,0)))+row("吸収総量",format(state.player.totalAbsorbed))}
function renderSkills(){const learned=Object.keys(state.player.skills);$("skillSlots").innerHTML=state.player.skillSlots.map((name,i)=>`<div class="skill-slot"><strong>${i+1}枠</strong><select data-slot="${i}"><option value="">未セット</option>${learned.map(s=>`<option value="${s}" ${s===name?"selected":""}>${s}</option>`).join("")}</select></div>`).join("");document.querySelectorAll("[data-slot]").forEach(sel=>sel.onchange=()=>setSkillSlot(Number(sel.dataset.slot),sel.value));$("learnedSkills").innerHTML=learned.map(n=>{const s=state.player.skills[n],set=state.player.skillSlots.includes(n);return `<article class="card"><h3>${n} Lv${s.level}${set?"【セット中】":""}</h3><p>技経験値：${format(s.exp)} / ${format(s.nextExp)}<br>消費MP：${SKILL_LIBRARY[n]?.mp??"-"}</p><div class="card-actions"><button data-unskill="${n}" ${!set?"disabled":""}>外す</button></div></article>`}).join("");document.querySelectorAll("[data-unskill]").forEach(b=>b.onclick=()=>unequipSkill(b.dataset.unskill))}
function renderMaterials(){const e=Object.entries(state.player.materials).filter(([,v])=>v>0);$("materials").innerHTML=e.length?e.map(([k,v])=>row(k,format(v))).join(""):row("素材","なし")}
function renderShop(){$("shopItems").innerHTML=SHOP_ITEMS.map(it=>{const owned=it.type!=="consumable"&&state.player.inventory[it.id],stats=it.stats?Object.entries(it.stats).map(([k,v])=>`${label(k)}+${format(v)}`).join(" / "):`回復薬+${it.amount}`;return `<article class="card"><h3>${it.name}${owned?"【所持】":""}</h3><p>${format(it.price)}G<br>${stats}</p><div class="card-actions"><button data-buy="${it.id}" ${state.player.money<it.price?"disabled":""}>購入</button>${it.slot&&owned?`<button data-equip="${it.id}">装備</button>`:""}</div></article>`}).join("");document.querySelectorAll("[data-buy]").forEach(b=>b.onclick=()=>buy(b.dataset.buy));document.querySelectorAll("[data-equip]").forEach(b=>b.onclick=()=>equip(b.dataset.equip))}
function renderCraft(){$("craftItems").innerHTML=CRAFT_RECIPES.map(r=>{const mats=Object.entries(r.materials).map(([m,a])=>`${m} ${mat(m)}/${a}`).join(" / "),stats=Object.entries(r.stats).map(([k,v])=>`${label(k)}+${format(v)}`).join(" / "),can=state.player.money>=r.costMoney&&Object.entries(r.materials).every(([m,a])=>mat(m)>=a),owned=state.player.inventory[r.id];return `<article class="card"><h3>${r.name}${owned?"【所持】":""}</h3><p>費用：${format(r.costMoney)}G<br>素材：${mats}<br>${stats}</p><div class="card-actions"><button data-craft="${r.id}" ${!can?"disabled":""}>作成</button>${owned?`<button data-equip="${r.id}">装備</button>`:""}</div></article>`}).join("");document.querySelectorAll("[data-craft]").forEach(b=>b.onclick=()=>craft(b.dataset.craft));document.querySelectorAll("[data-equip]").forEach(b=>b.onclick=()=>equip(b.dataset.equip))}
function renderEquipment(){const names={weapon:"武器",armor:"防具",accessory:"装飾"};$("equipment").innerHTML=Object.entries(state.player.equipment).map(([s,id])=>row(names[s],id?findItem(id).name:"なし")).join("")}
function renderParty(){$("partyList").innerHTML=ALLIES.map(a=>{const joined=state.unlockedAllies[a.id],can=a.canJoin(),bonus=Object.entries(a.bonus).map(([k,v])=>`${label(k)}+${format(v)}`).join(" / ");return `<article class="card"><h3>${a.name}${joined?"【加入済】":""}</h3><p>条件：${a.requirementText}<br>効果：${bonus}</p><button data-join="${a.id}" ${joined||!can?"disabled":""}>仲間にする</button></article>`}).join("");document.querySelectorAll("[data-join]").forEach(b=>b.onclick=()=>join(b.dataset.join))}
function renderQuests(){$("quests").innerHTML=QUESTS.map(q=>{const claimed=state.claimedQuests[q.id],done=q.done();return `<article class="card"><h3>${q.name}${claimed?"【達成済】":done?"【達成可能】":""}</h3><p>${q.description}</p><button data-quest="${q.id}" ${claimed||!done?"disabled":""}>報酬受取</button></article>`}).join("");document.querySelectorAll("[data-quest]").forEach(b=>b.onclick=()=>{const q=QUESTS.find(x=>x.id===b.dataset.quest);if(!q||state.claimedQuests[q.id]||!q.done())return;state.claimedQuests[q.id]=true;q.reward();log(`クエスト達成「${q.name}」！`,"rare");render()})}
function renderImages(){const saved=localStorage.getItem(HERO_IMAGE_KEY);$("heroImage").src=saved||"./assets/hero-sprite-sheet.png";$("heroImage").classList.add("show")}
function row(a,b){return `<div class="row"><span>${a}</span><strong>${b}</strong></div>`}function bar(a,v,m){const p=Math.max(0,Math.min(100,(v/Math.max(1,m))*100));return `<div class="bar-label">${a}: ${format(v)} / ${format(m)}</div><div class="bar"><div class="bar-fill" style="width:${p}%"></div></div>`}function label(k){return{maxHp:"HP",maxMp:"MP",atk:"攻撃",def:"防御"}[k]||k}
function log(text,type=""){const d=document.createElement("div");d.className=`log-entry ${type}`;d.textContent=text;$("log").prepend(d);while($("log").children.length>140)$("log").removeChild($("log").lastChild)}
function anim(el,cls){if(!el)return;el.classList.remove(cls);void el.offsetWidth;el.classList.add(cls)}
function heroSlash(){anim($("heroImage"),"attack");anim($("heroFallback"),"flash")}
let toastTimer=null;function toast(t){clearTimeout(toastTimer);$("toast").textContent=t;$("toast").classList.remove("hidden");toastTimer=setTimeout(()=>$("toast").classList.add("hidden"),1600)}
function setupAudio(){if(audio.ctx)return;audio.ctx=new (window.AudioContext||window.webkitAudioContext)()}
function tone(freq,dur,type="sine",gain=.05){if(!audio.enabled)return;setupAudio();const ctx=audio.ctx,o=ctx.createOscillator(),g=ctx.createGain();o.type=type;o.frequency.value=freq;g.gain.value=gain;o.connect(g);g.connect(ctx.destination);o.start();g.gain.exponentialRampToValueAtTime(.001,ctx.currentTime+dur);o.stop(ctx.currentTime+dur)}
function sfx(kind){if(!audio.enabled)return;const map={attack:[220,.08,"sawtooth",.045],skill:[440,.16,"triangle",.055],hit:[90,.08,"square",.035],win:[660,.12,"sine",.05],level:[880,.22,"triangle",.055],coin:[1040,.07,"sine",.04],heal:[520,.14,"sine",.04],absorb:[330,.18,"triangle",.05],learn:[990,.28,"sine",.05],equip:[740,.09,"triangle",.04],craft:[600,.16,"triangle",.05],move:[260,.08,"sine",.035],spawn:[140,.12,"sawtooth",.03],down:[70,.22,"sawtooth",.045]};const a=map[kind]||map.coin;tone(...a)}
function startBgm(){if(!audio.enabled)return;setupAudio();stopBgm();const notes=[220,247,262,330,294,262,247,196];let i=0;audio.bgmTimer=setInterval(()=>{tone(notes[i%notes.length],.18,"triangle",.018);i++},420)}
function stopBgm(){if(audio.bgmTimer){clearInterval(audio.bgmTimer);audio.bgmTimer=null}}
function toggleAudio(){audio.enabled=!audio.enabled;$("audioBtn").textContent=audio.enabled?"音OFF":"音ON";if(audio.enabled){setupAudio();audio.ctx.resume();startBgm();toast("BGM/効果音ON")}else{stopBgm();toast("BGM/効果音OFF")}}
function bind(){document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>tab(b.dataset.tab));$("audioBtn").onclick=toggleAudio;$("saveBtn").onclick=save;$("loadBtn").onclick=load;$("resetBtn").onclick=reset;$("absorbSomeBtn").onclick=()=>absorb("some");$("absorbAllBtn").onclick=()=>absorb("all");document.querySelectorAll("[data-sell]").forEach(b=>b.onclick=()=>sell(b.dataset.sell));$("heroUpload").onchange=e=>{const file=e.target.files&&e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{localStorage.setItem(HERO_IMAGE_KEY,reader.result);renderImages();toast("主人公画像を変更")};reader.readAsDataURL(file)};$("resetHeroImageBtn").onclick=()=>{localStorage.removeItem(HERO_IMAGE_KEY);renderImages();toast("主人公画像を初期化")}}
bind();migrate();log("v0.2開始。BGM/効果音、画像、魔石一括吸収、技セット9枠を追加。");spawnEnemy();render();
})();
